version: '3.8'

services:
  mysql:
    image: mysql:8.0.31
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurants_booking


  mail-dev:
    container_name: mail-dev-restaurants
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  app:
    image:
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurants_booking?autoReconnect=true&allowPublicKey Retrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root


