spring:
  datasource:
#    url: jdbc:mysql://grandpittu-restaurant-booking.cale2qc4qfp1.us-east-1.rds.amazonaws.com:3306/grandpittu-restaurant-booking
#    username: admin
#    password: Cchayan123
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurants_booking
    username: root
    password: MYsql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect  # changed from deprecated MySQL8Dialect
    open-in-view: false

  mail:
    host: smtp.zoho.com
    port: 587
    username: info@grandpittu.lk
    password: 3G5MuxR41EzM
    from: info@grandpittu.lk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          trust: "*"
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: finspire001@gmail.com
#      password: dkpalajggmhwviqq
#      from: finspire001@gmail.com
#      properties:
#        mail.smtp.auth: true
#        mail.smtp.starttls.enable: true
#        mail.smtp.starttls.required: true
#        mail.smtp.connectiontimeout: 5000
#        mail.smtp.timeout: 3000
#        mail.smtp.writetimeout: 5000



application:
  security:
    jwt:
      secret-key: eEy9ZzQvmvjnzX0WtVGqCdmdspgYDgSx00tC0DIRFKvlq1N6JjSDYyVzKsQ3TKK5
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

notifylk:
  userId: 29960
  apiKey: M83L5EdCJmZeTSCJMEx5
  senderId: NotifyDEMO


#spring.jackson.serialization.indent-output=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB